### ISSUE TITLE
disconnected upon shooting a spawned dummy

### ISSUE THREAD

**Issue by Firexik** [Exiled-Team/AdminTools#36] opened 2021-12-28 16:18 UTC
**Describe the bug**
upon shooting a spawned dummy the server will disconnect you upon shooting it

**To Reproduce**
1. spawn a dummy
2. shoot it
3. congrats, you got yeeted out from the server

**Expected behavior**
being able to shoot the dummy without getting disconnected

**Server logs: https://pastebin.com/PbFbQ6RP**

**EXILED Version: 4.1.7**

**Results of `show plugins` command in console: https://imgur.com/a/3xYsvdP**

**Additional context**
-

**Comment by joker-119** [comment] 2021-12-28 19:14
Duplicate of #29

**Closed by joker-119** 2021-12-28 19:14 UTC
